[package]
name = "rust_serial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
serialport = "4.2.0"
zerocopy = "0.6.1"
